# Disable all metrics.
Metrics:
  Enabled: false

# Disable warning about using eval.
Security/Eval:
  Enabled: false

# Disable message about empty lines in the emd of module
Layout/EmptyLinesAroundModuleBody:
  Enabled: false
