---
# Discord API client ID
client_id:

# Discord API client token
token:

# Command prefix
prefix:

# ID of bot owner
owner:

# game the bot is playing
game:

# Youtube API client key
youtube_key:

# Server & Channel IDs
server_id:
channel_id:
