---
# Discord API client token
token:

# Command prefix
prefix:

# Bot owner's ID
owner_id:

# Bot's playing status
game:

# Youtube API client key
youtube_key:

# Music logs Channel ID
channel_id:

# QnA Credentials
knowledgebase_id:
subscription_key:

# Mee6 API key
mee6_api:
